Title =  "listenlive.cn"
LanguageCode = "zh-CN"
BaseUrl = "https://listenlive.cn"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh"

[Params]
  Introduce = "Programmer & Architect"
  Description = "博客 | 软件 | 架构 | PHP | 开发 | Hugo | Golang | go | Node.js"
  Keywords =  "独立,博客,程序员,个人,开发,思考,读书,笔记,技术,分享,PHP,Hugo,Node.js,Golang"
  Subtitle = "too young too simple"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  #百度统计
  BaiduStatsId = "2444*********"
  #腾讯移动分析
  QQStatsId = "5007*****"
  #访客地图
  RevolverMapId = "5t3m*****"
  Fancybox = true
  rss = "/index.xml"
[Author]
  Name = "黑貓警長"
[Params.Share]
  Baidu = true
#Valine 留言板  
[Params.valine]
    enable = true
    appId = '9iO******'
    appKey = 'U2*********'
    notify = false
    verify = false
    avatar = 'mm'
    placeholder = '说点什么吧...'
    visitor = true
	
[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "技术"
  Pre = "code"
  URL = "/categories/技术/"
  Weight = 2
[[Menu.Main]]
  Name = "笔记"
  Pre = "book"
  URL = "/categories/笔记/"
  Weight = 3
[[Menu.Main]]
  Name = "杂记"
  Pre = "leaf"
  URL = "/categories/杂记/"
  Weight = 4
[[Menu.Main]]
  Name = "分享"
  Pre = "share"
  URL = "/categories/分享/"
  Weight = 5
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 6
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 7
[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com"
[[Params.Socials]]
  Name = "Instagram"
  Icon = "instagram"
  #Icon = "globe"
  URL = "https://www.instagram.com/ins0273"
[[Params.Socials]]
  Name = "Weibo"
  Icon = "weibo"
  URL = "https://weibo.com/u/6515305531" 
[[Params.Socials]]
  Name = "Gmail"
  Icon = "envelope"
  URL = "mailto:listenlive7@gmail.com"